dapphub/klab

README.md, libexec/klab-run
For better integration with dapp/solc
=> Extract sourcemap and binary from .sol.json

lib/displayHandler.js, lib/local_tmp.js, lib/show.js, lib/stateHandler.js
Uses the new structured JSON output that K supports at:
https://github.com/kframework/evm-semantics/tree/state-dumps
=> New json format

.gitignore, Makefile, examples/SafeAdd/spec.ini, lib/driver/kDriver.js, media/introduction.md
Includes the presentation I used to make a video of KLab (which I'll release soon).
Also decreases the Z3 default implication timeouts (which didn't seem to actually do anything).
=> Presentation

libexec/klab-get-gas
this replaces gas rebased rebased branch
=> New gas work

lib/build.js, lib/driver/dbDriver.js, libexec/klab-build, libexec/klab-compile
=> Build improvements2

lib/kast.js, libexec/klab-build, shell.nix
Wow, I love this one. :heart_eyes:
=> This is a very nice version of klab, with many user friendly features and great performance

Dockerfile, Makefile
This associates the submodule commit to a branch, which will hopefully resolve some of the issues like #145.
=> evm-semantics: bump submodule commit

README.md, examples/SafeAdd/config.json, examples/d0_suck/config.json, examples/multipleCalls/config.json, examples/token/config.json
Updated for the new architecture. Also made some changes I think will improve the clarity.
=> refactor readme

lib/move.js
I expect to be able to exit with :q when there is a vim-like command line. Not sure if any cleanup needs to be done on exit? @mhhf
=> debug: exit with :q

lib/build.js
I'll make an accompanying PR to evm-semantics shortly.
=> support all sizes of signed and unsigned integers from solidity

libexec/klab-prove-all, resources/rules.k.tmp
Came across the need for this in `k-osm`.
=> Bitshift identities

libexec/klab-prove, libexec/klab-prove-all
~no merge plz~ review and merge plz
=> catch+propagate SIGTERM on blocking children in prove and prove-all

libexec/klab-get-x
=> WIP cosolving gas (get-gas)

.gitignore, haskell/k-gas-analyser.cabal, haskell/src/Analyser.hs, haskell/src/Gas.hs, haskell/src/Kast.hs, haskell/src/KastParse.hs, haskell/src/Solver.hs, haskell/src/Test.hs, klab.nix, lib/build.js, libexec/klab-solve-gas
Raw gas stratification is here.
=> more generic gas analyser

package.json
package.json had an incorrect `name` value
=> rename the package.json name to klab

lib/build.js, lib/kjson.js, libexec/klab-build-js
=> first iteration of kicking out the haskell solver

libexec/klab-get-lemmas, libexec/klab-get-refund, libexec/klab-get-x, libexec/klab-prove, libexec/klab-prove-all
=> configurable timeouts

acts.md
Explain what the `calls` block is for.
=> doc: calls

lib/config.js
Check that the variable is initialized before using it.
=> lib/config.js: check presence of contract early

README.md
=> adds jq to osx dependencies

lib/build.js
Resolves https://github.com/dapphub/klab/issues/230
=> build.js: remove splitting functionality

resources/rules.k.tmp
PR to see if it breaks anything else.
=> add rule which allows for abstract wordstack in memory

lib/kast.js
Adds a few more constants and infix operators to `kast.js`
=> add pow32 and _modInt_ infix

libexec/klab-prove
=> make compatible with latest z3

.gitmodules
=> evm-semantics: move to dapphub fork

libexec/klab-report, resources/overview.js
Add git commit to overview, unstyled.
Closes #309.
=> Report git commit

libexec/klab-setup-ci-project, resources/overview.js, resources/overview.scss
This fixes the link introduced in #310.
=> Fix git link

lib/util.js
=> util: add timestamp to build_hash

acts.md
Spent quite a while debugging a spec that was rejected because of this today.
The description here feels a little wordy, open to suggestions on making it more concise.
=> acts.md: document isStatic

.gitignore, package-lock.json, package.json
Just a lil bit of `npm` housekeeping:
- commit `package-lock.json` (deterministic builds :sparkles: :smile_cat:) 
- bump `marked` to squash the vulnerability warning on install
=> npm: housekeeping

libexec/klab-prove-all
This salmon is out of date :yum:
=> prove-all: remove outdated code

README.md
=> Document limits

README.md, lib/build.js
And save magic number in a constant.
=> Document max gas
