README.md

TMPDIR is not universal for Linux systems

README: document that TMPDIR must be set

---

Makefile

Minor fix, this environment variable was causing `make deps` to fail on one machine.

Makefile: don't set TMPDIR, can cause build issues

---

Makefile
examples/multipleCalls/Makefile
lib/kast.js
libexec/klab-build

A new `Makefile` compatible with batched proofs. 
To test this out:
```sh
cd examples/multipleCalls
make -j2
```
If this one looks good we can use the same `Makefile` for all of the examples, there's nothing in it that's specific to `multipleCalls`. Each example can have a `Makefile` consisting of `import ../../resources/example.Makefile`.

 multipleCalls/Makefile: uses new batched proof scheme 

---

README.md

The path for `git clone` in the `README.md` works only for users in the dapphub organisation. 
Updated to work for all users.

Update git repository path in README.md

---

libexec/klab-prove

The trick is to add `<storage>` to `--output-tokenize`. `==K` also needs to be removed because it's used for gas analysis now.

fix storage display in proofs generated with klab prove --dump

---

examples/SafeAdd/Makefile
examples/d0_suck/Makefile
examples/multipleCalls/Makefile
examples/multipleCalls/src/specification.act.md
examples/token/Makefile

I noticed that this spec was not general enough, in that the initial value of slot `0` in `Callee` was assumed to be `0`. I think there is value to this example having branching, which otherwise it doesn't have, since it would then be a better test of spec-lemma application, gas behaviour display, etc., so I'm proposing to make this spec fully general by abstracting `Temperature`.
Also, this is a useful test case to keep in mind when thinking about what can make specs non-exhaustive: we must remember that the way that you phrase the precondition can have certain unjustified assumptions...

examples/multipleCalls: generalise the spec

---

lib/kast.js

The current infix notation can be ambiguous when multiple operations are composed. Enclosing every operation in a set of parens fixes this, although we could try to be smarter about when it's necessary.

show order of operations in pretty printing

---

lib/build.js
resources/rules.k.tmp

With https://github.com/kframework/k/commit/d665d8c756efabe01b50a995f75723d6dcc7b448,
and since `MAP` module included in evm-semantics is the symbolic version, we no longer have to rely on our own `+Map` to ensure that things go wrong when there is a possible storage collision. An update to storage `M [K <- V]` will only simplify if K is provably not present in M. This was not the case before.

Use builtin symbolic-map rather than +Map hack

---

lib/behavior.js

With this fix klab inspection doesn't crash when certain EVM specific features are not present.

Add safety check around EVM-specific features

---

haskell/src/Analyser.hs
haskell/src/Gas.hs
haskell/src/Kast.hs
haskell/src/KastParse.hs
haskell/src/Solver.hs
lib/build.js
libexec/klab-get-gas
libexec/klab-get-refund
libexec/klab-solve-gas
resources/rules.k.tmp

Now we just need @mhhf to integrate this with `klab`.
n.b. that the input is now expected to be a JSON array of raw gas
kasts, and the output will always be in array form.
With stratification (the default), the "constructors" field (which
used to be called "constructor") will be an array of strings like
`["#G0", "#G1", ..., "#Gn"]`, and should be interpreted as a list of
lower bounds for the initial gas, i.e. should translate into a
condition like `(VGas >=Int #G0) andBool ... andBool (VGas >=Int #Gn)`.
With the flag `--no-stratify`, the output will be an array of strings,
corresponding to the unstratified gas expressions.

gas analyser: refund support (now everything is arrays)

---

resources/rules.k.tmp

Would change `out/rules` and trigger a rerun of all ci proofs, so we should be careful with merging this one.

rules.k: remove unnecessary lemmas

---

README.md

This causes naively running the command in the README to fail.

remove 'v' as it isn't in current tag name

---

libexec/klab-build-js
libexec/klab-report

Adding an error throw if `KLAB_EVMS_PATH` does not end in `evm-semantics`

Add error for bad klab evms path

---

libexec/klab-prove

I thought this was a helpful flag to have available rather than manually editing the prove file to add the flag

allow flagging k --debug via klab prove --kdebug

---

shell.nix

It fails otherwise in mac osx using `nix-shell --pure`

Add bc to shell.nix

---

README.md

Oracle distribution of "java8" has ceased to be available: https://stackoverflow.com/questions/55834845/unable-to-install-java8-with-homebrew
Repointing cask installation to https://github.com/AdoptOpenJDK/homebrew-openjdk

Update for MacOS installation instructions.

---

shell.nix

`nodejs-8_x` is not recognized anymore (I'm using Nix 2.3 installed today). Updating to `nodejs-10_x` although 11 or 12 could be used too (haven't tested them).

Use Node 10

---

lib/build.js
lib/config.js
libexec/klab-report

A couple of small changes that let `klab` play nice with [waffle](https://github.com/EthWorks/Waffle) based projects.
- add a `solc_output` key to the config.json to allow integration with build systems that name their solc json output something other than `dapp.sol.json`
- handle both stringified and non stringified abi specifications in solc output (contract abis generated by waffle according to the instructions [here](https://ethereum-waffle.readthedocs.io/en/latest/configuration.html#klab-compatibility) are not stringified, those output with `solc --combined-json=abi,bin,bin-runtime,srcmap,srcmap-runtime,ast` are).
Having `klab` support multiple json output formats is kinda messy, but I played around with the various options for a while and couldn't figure out how to bring it inline …

Support waffle based build systems

---

shell.nix

`klab` is currently broken with `nixpkgs@unstable` (see https://github.com/dapphub/klab/issues/295). This commit pins us to a known good revision of `nixos-19.09` in `shell.nix`

shell.nix: pin to nixos-19.09

---

resources/k.json

Allow usage of `BLOCK_NUMBER` in `act` specs to refer to `block.number`

k.json: add BLOCK_NUMBER

---

lib/build.js

Maybe there is a cleaner way to do this, but with this change I can split very long `K` statements (especially `#if ... #then ... #else ... #fi` blocks) over multiple lines, so something like:
```
storage
value |-> Value => #if Condition1 =/= 0 and Condition2 =/= 0  #then Value +Int (pow32 &Int OtherValue) /Int YetAnotherValue #else Value #fi
```
becomes
```
storage
value |-> Value => #if Condition1 =/= 0 and Condition2 =/= 0  \
#then Value +Int (pow32 &Int OtherValue) /Int YetAnotherValue \
#else Value \
#fi
```

RFC: act: multiline statments

---

README.md

Document `config.json`.
As a temporary substitute for #301.
Later on we can document each key.

doc: config.json

---

shell.nix

Cf. https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory
Only in `shell.nix` for now. If this turns out to be very useful we can move it to klab proper.

shell.nix: bump memory cap to 4GiB

---

shell.nix

Adds a couple of missing dependencies.

shell.nix: allow execution with nix-shell --pure

---

README.md

We experimented with stable releases for a while but I think the most manageable thing is to just instruct users to use `master`.
If certain projects require an older version of `klab` then they should specify themselves which revision to use.

README.md: just instruct the user to use master

---

shell.nix

Adds `pkgs` to the `passthru`, making it available for projects importing `shell.nix`.
This allows them to ensure they are always using the "official" nixpkgs version for `klab`.

nix: allow consuming projects to reuse our nixpkgs

---

Makefile

They're needed for the gas analyzer, which is almost always used.

Makefile: build haskell dependencies by default

---

README.md

This reverts commit f31e24e0da5746f69e57f362445765210f6ae484.
The reason is that klab master is currently partially broken after merging #318.

README: mention v0.4.0

---

lib/view.js

This fixes a case in which the `max_step` was `NaN`.
This is a hack, since `getHeights` gets called recursively and it might
therefore be necessary to check for the property's existence in
`getHeights` itself.

view: check endheight is defined

---

libexec/klab-prove

Prints out useful information, like the following, plus a bunch of other stuff.
Produces *really huge* logs (~18MB on `token0`).
```
[nix-shell:~/code/dapphub/k-uniswap-v2]$ klab prove --kdebug UniswapV2Exchange_token0_pass_rough
Using evm-semantics from /home/asymmetric/code/dapphub/k-uniswap-v2/deps/klab/evm-semantics
Proof STARTING: abf7e62979d0976a6af1ad21b44b576336368cec815dfda2419e70c36b127f6e.k [UniswapV2Exchange_token0_pass_rough]
Importing: Source(/home/asymmetric/code/dapphub/k-uniswap-v2/././out/specs/abf7e62979d0976a6af1ad21b44b576336368cec815dfda2419e70c36b127f6e.k)
Importing: Source(/home/asymmetric/code/dapphub/k-uniswap-v2/out/specs/abf7e62979d0976a6af1ad21b44b576336368cec815dfda2419e70c36b127f6e.k)
Importing: Source(/home/asymmetric/code/dapphub/k-uniswap-v2/out/rules.k) …
```

klab-prove: add debug-z3 flag

---

libexec/klab-prove-all
libexec/klab-setup-ci-project

The idea with this PR is that the `prove-all` command keeps on working as before (i.e. it only copies files if they're not there already), because we don't want a local klab (e.g. in k-dss) to overwrite global reports dirs.
OTOH, the `klab-setup-ci-project` script can be run on a new CI (without the `--project-name` argument) to actually set up a CI for the first time - or to make global changes. In our buildbot case, this would look like:
```bash
$ cd klab && nix-shell
$ klab-setup-ci-project --report-dir /var/publish/reports
```
We could add this to the `Makefile`, theoretically,
This PR also adds SCSS asset pre-processing.

klab-setup-ci-project: make deploys easier

---

libexec/klab-build-js

klab-build-js: use klab commit hash for proof hash

---

resources/rules.k.tmpl

This PR bumps evm-semantics to include [this commit](https://github.com/dapphub/evm-semantics/commit/851b6df9e3ecd74f4a8c6dbb42a96c81b73c284a), which simplifies `sizeWordStack`, removes `sizeWordStackAux`, and obviates the need for our own rules in `rules.k.tmpl`.

Remove additional sizeWordStack rules

---

libexec/klab-prove-all

Ensures that the report location is shown even when `KLAB_REPORT_DIR` is not
set.

klab-prove-all: always print report location

---

lib/util.js

This reverts commit ca50eb35c50343b3772596b50bed49abaf03aa6c.
`getBuildId` is called multiple times as part of klab-prove-all, and incorporating a timestamp meant that it returned a different result each time, messing up the reports in CI.

Revert "util: add timestamp to build_hash"

---

libexec/klab-prove-all

`KLAB_REPORT_PROJECT_DIR` did not exist, and so the `cp` in [`report()`](https://github.com/dapphub/klab/blob/9f035f4ec58d7a7d862b9dbd91e9a1636dbde4e6/libexec/klab-prove-all#L64) was writing the `index.html` to `KLAB_REPORT_PROJECT_DIR` as a file, instead of as a
file inside of `KLAB_REPORT_PROJECT_DIR`.
This was resulting in messed up reports in CI. This commit ensures the report directory always exists.

klab-prove-all: ensure report dir exists

---

libexec/klab-prove

This fixes some broken specs that were passing before we bumped the evms.

klab-prove: make padRightToWidth symbolic

---

.envrc
shell.nix

- Support `lorri` in `shell.nix`
- Add a `.envrc` and use `lorri` if available

meta: use direnv

---

lib/build.js
libexec/klab-build-js

Uses the same proof hash calculation algorithm for the exhaustiveness specs as the "normal" specs.
Should hopefully fix some cache invalidation issues in CI by forcing new runs for exhaustiveness specs when the klab commit changes.

build.js: unify proof hash calculation

---

lib/build.js

Fixes for a few anomalies on the html report:
- Don't duplicate creates storage blocks
- Don't rewrite creates storage blocks
- Don't render empty storage block `doc:` comments
- Replace left bitshift with html entities

Report formatting

---

shell.nix

Used in klab-fetch.
We could also use [atool](https://www.nongnu.org/atool/), which replaces zip and
unzip.

shell.nix: add unzip to buildInputs

---

resources/k.json

It's never possible for a contract to have address 0, so we shouldn't waste any time exploring this possibility in proofs.

resources/k.json: assert ACCT_ID is never 0

---

shell.nix

This gives us z3 4.8.7, which includes a fix for [this issue](https://github.com/Z3Prover/z3/issues/2458) that has probably caused a few of our uniswap proofs to fail.

shell.nix: bump nixpkgs to 20.03

---

lib/kast.js

variables that were present in the spec and are not runtime variables are included in the antimatch view if they dont match. May include false positives.

fix antimatch view - include variable diffs

---

lib/formatmemory.js

Use `=` instead of `-`, which looks like part of the expression.
Used when showing long variable placeholders in the memory view.

lib/formatmemory.js: use = for var placeholders

---

package-lock.json
package.json

runs `npm audit fix` to squash `minimist` related security warnings.

Squash security warnings`

---

resources/rules.k.tmpl

Showed up as one of the warnings of undefined var on RHS.

rules.k.tmpl: fix typo in keccakIntList

---

libexec/klab-report

Rather than hardcoded dapp.ci.
Also switches to HTTPS.

libexec/klab-report: use config.host

---

lib/behavior.js

Shows an x in the behaviour tree for branches terminating with an invalid instruction. This happens on e.g. divide by zero.

lib/behaviour.js: show X for invalid opcodes

---

libexec/klab-prove-all

Git supports multiple worktrees per repository (`git worktree add <PATH>`). When inside one of these worktrees .git is a file pointing to the directory containing the repository (gitdir: <PATH>) instead of a
directory and so prove-all did not setup the ci project as expected.

prove-all: support running in a worktree

---

lib/build.js
resources/k.json

Makes the precompiles consistent with the lemmas in `rules.k.tmpl`, which assume that 9 precompiles exist.

add blake2 precompile

---

libexec/klab-report

The call to `read()` was reading the whole file in memory, which would
explode at runtime for very long logs.
This commit removes the check on empty files, which could result in
links being shown in the report page that are effectively useless.
The ideal solution would be to use something like Node's `Stream` class,
to perform the same check without loading everything in memory. Decided
not to implement this for now, as the feature being removed doesn't seem
important enough to warrant spending the necessary time dealing with Node.js in
order to re-implement it with Streams.
Let me know what you think.

libexec/klab-report: stop checking for empty files

---

lib/build.js
lib/kast.js

`kast.format` is used to format gas expressions for use in `pass` specifications; recent changes (see #413) introduced changes that make the output of `format` unparseable by `K`.
This PR introduces a variable that can be used to differentiate between pretty-printing and generating valid `K` syntax for use in specifications, and applies it conservatively to prevent issues (i.e. there may be other situations in which it should be used, I didn't try to be exhaustive here).

Format fix

---

lib/kast.js

This should fix the failure [here](https://dapp.ci/k-uniswap/378f3c7c7eff002f643b/#UniswapV2Pair_sync())

don't pretty-print wordpacks in gas expressions

---

lib/build.js
resources/k.json

This is conflicting when running proofs with other proofs as lemmas. Per @MrChico " the assumption that `ACCT_ID =/= 0` might not be provable for other contracts"

Remove assert ACCT_ID is never 0
